// Package harbor_inst/client.go was generated by codegen, please fix its package dependency, but do not modify its functionality
package harbor_inst

import (
	"context"
	"github.com/Juminiy/kube/pkg/image_api/harbor_api"
	"github.com/Juminiy/kube/pkg/util"
	"github.com/goharbor/go-client/pkg/sdk/v2.0/client/artifact"
	"github.com/goharbor/go-client/pkg/sdk/v2.0/client/project"
	"github.com/goharbor/go-client/pkg/sdk/v2.0/client/repository"
	"github.com/goharbor/go-client/pkg/sdk/v2.0/client/user"
	"github.com/goharbor/go-client/pkg/sdk/v2.0/models"
	"net/http"
)

func CopyArtifact(artifactURI harbor_api.ArtifactURI, artifactURI2 harbor_api.ArtifactURI) (*artifact.CopyArtifactCreated, error) {
	return _harborClient.CopyArtifact(artifactURI, artifactURI2)
}

func CreateAdmin(userCreationReq *models.UserCreationReq) (*user.CreateUserCreated, error) {
	return _harborClient.CreateAdmin(userCreationReq)
}

func CreateArtifactTag(artifactURI harbor_api.ArtifactURI, artifactURI2 harbor_api.ArtifactURI) (*artifact.CreateTagCreated, error) {
	return _harborClient.CreateArtifactTag(artifactURI, artifactURI2)
}

func CreateProject(projectReqConfig harbor_api.ProjectReqConfig) (*project.CreateProjectCreated, error) {
	return _harborClient.CreateProject(projectReqConfig)
}

func DeleteAdmin(_int64 int64) (*user.DeleteUserOK, error) {
	return _harborClient.DeleteAdmin(_int64)
}

func DeleteArtifact(artifactURI harbor_api.ArtifactURI) (*artifact.DeleteArtifactOK, error) {
	return _harborClient.DeleteArtifact(artifactURI)
}

func DeleteProject(_string string) (*project.DeleteProjectOK, error) {
	return _harborClient.DeleteProject(_string)
}

func ExportArtifact() (string, error) {
	return _harborClient.ExportArtifact()
}

func GC(varLenfunc ...util.Func) {
	_harborClient.GC(varLenfunc...)
}

func GenerateArtifact() error {
	return _harborClient.GenerateArtifact()
}

func GetArtifact(artifactURI harbor_api.ArtifactURI) (*artifact.GetArtifactOK, error) {
	return _harborClient.GetArtifact(artifactURI)
}

func GetAuth() (string, error) {
	return _harborClient.GetAuth()
}

func ImportOfflineArtifact() error {
	return _harborClient.ImportOfflineArtifact()
}

func ListArtifacts(artifactURI harbor_api.ArtifactURI) (*artifact.ListArtifactsOK, error) {
	return _harborClient.ListArtifacts(artifactURI)
}

func ListProjects() (*project.ListProjectsOK, error) {
	return _harborClient.ListProjects()
}

func ListRepositories(_string string) (*repository.ListRepositoriesOK, error) {
	return _harborClient.ListRepositories(_string)
}

func WithCallBack(callBack *harbor_api.CallBack) *harbor_api.Client {
	return _harborClient.WithCallBack(callBack)
}

func WithContext(context context.Context) *harbor_api.Client {
	return _harborClient.WithContext(context)
}

func WithHttpClient(client *http.Client) *harbor_api.Client {
	return _harborClient.WithHttpClient(client)
}

func WithPageConfig(page *util.Page) *harbor_api.Client {
	return _harborClient.WithPageConfig(page)
}
