log:
  engine: zap
  zap:
    level: info
    caller: true
    stacktrace: true
    path:
      - /Users/chisato/go/src/kube/cmd/menud/log/app.log
    internalPath:
      - /Users/chisato/go/src/kube/cmd/menud/log/app_zero.log
  zero:
    level:
    path:

harbor:
  registry: http://harbor.local:18111
  username: admin
  password: bupt.harbor@666
  public: public

docker:
  host: tcp://docker.local:12375
  version: 1.43

kubernetes:
  kubeConfigPath: ~/.kube/config

minio:
  endpoint: 192.168.31.66:19000
  accessKeyID: bupt.minio@666
  secretAccessKey: bupt.minio@666
  secure: false