// Package docker_inst/client.go was generated by codegen, do not modify it
package docker_inst

import (
	"context"
	"github.com/Juminiy/kube/pkg/image_api/docker_api"
	"github.com/Juminiy/kube/pkg/util"
	"github.com/docker/docker/api/types"
	"io"
)

func CreateImageTag(_string string, _string2 string) (io.ReadCloser, error) {
	return _dockerClient.CreateImageTag(_string, _string2)
}

func ExportImage(_string string) (io.ReadCloser, error) {
	return _dockerClient.ExportImage(_string)
}

func HostImageGC(hostImageGCFunc docker_api.HostImageGCFunc) {
	_dockerClient.HostImageGC(hostImageGCFunc)
}

func ImportImage(_string string, reader io.Reader) (io.ReadCloser, error) {
	return _dockerClient.ImportImage(_string, reader)
}

func ListContainerFullIds() ([]string, error) {
	return _dockerClient.ListContainerFullIds()
}

func ListContainerIds() ([]string, error) {
	return _dockerClient.ListContainerIds()
}

func ListContainerNames() ([]string, error) {
	return _dockerClient.ListContainerNames()
}

func ListContainers() ([]types.Container, error) {
	return _dockerClient.ListContainers()
}

func WithContext(context context.Context) *docker_api.Client {
	return _dockerClient.WithContext(context)
}

func WithPage(page *util.Page) *docker_api.Client {
	return _dockerClient.WithPage(page)
}
