// Package docker_inst/client.go was generated by codegen, do not modify it
package docker_inst

import (
	"context"
	"github.com/Juminiy/kube/pkg/image_api/docker_api"
	"github.com/Juminiy/kube/pkg/util"
	"github.com/docker/docker/api/types"
)

func CreateTag() {
	_dockerClient.CreateTag()
}

func ListContainerFullIds() ([]string, error) {
	return _dockerClient.ListContainerFullIds()
}

func ListContainerIds() ([]string, error) {
	return _dockerClient.ListContainerIds()
}

func ListContainerNames() ([]string, error) {
	return _dockerClient.ListContainerNames()
}

func ListContainers() ([]types.Container, error) {
	return _dockerClient.ListContainers()
}

func PullImage() {
	_dockerClient.PullImage()
}

func PushImage() {
	_dockerClient.PushImage()
}

func WithContext(context context.Context) *docker_api.Client {
	return _dockerClient.WithContext(context)
}

func WithPage(page *util.Page) *docker_api.Client {
	return _dockerClient.WithPage(page)
}
