// Package minio_inst/client.go was generated by codegen, please fix its package dependency, but do not modify its functionality
package minio_inst

import (
	"context"
	"github.com/Juminiy/kube/pkg/storage_api/minio_api"
	"github.com/Juminiy/kube/pkg/util"
	"github.com/minio/minio-go/v7/pkg/credentials"
	"net/url"
	"time"
)

func AddIAMUser(value *credentials.Value) error {
	return _minioClient.AddIAMUser(value)
}

func AtomicWorkflow(req minio_api.Req) (minio_api.Resp, error) {
	return _minioClient.AtomicWorkflow(req)
}

func BatchDeleteAccessKey() {
	_minioClient.BatchDeleteAccessKey()
}

func BatchDeleteBucket() {
	_minioClient.BatchDeleteBucket()
}

func BatchDeletePolicy() {
	_minioClient.BatchDeletePolicy()
}

func CreateAccessKey() (credentials.Value, error) {
	return _minioClient.CreateAccessKey()
}

func DeleteAccessKey(_string string) error {
	return _minioClient.DeleteAccessKey(_string)
}

func DeleteAccessPolicy(policyConfig *minio_api.PolicyConfig) error {
	return _minioClient.DeleteAccessPolicy(policyConfig)
}

func GC(varLenfunc ...util.Func) {
	_minioClient.GC(varLenfunc...)
}

func ListAccessKey() {
	_minioClient.ListAccessKey()
}

func ListBucket() {
	_minioClient.ListBucket()
}

func ListCannedPolicy() {
	_minioClient.ListCannedPolicy()
}

func MakeBucket(bucketConfig *minio_api.BucketConfig) error {
	return _minioClient.MakeBucket(bucketConfig)
}

func RemoveBucket(bucketConfig *minio_api.BucketConfig) error {
	return _minioClient.RemoveBucket(bucketConfig)
}

func RemoveIAMUser(_string string) error {
	return _minioClient.RemoveIAMUser(_string)
}

func SetAccessPolicy(policyConfig *minio_api.PolicyConfig) error {
	return _minioClient.SetAccessPolicy(policyConfig)
}

func SetBucketPolicy(policyConfig *minio_api.PolicyConfig) error {
	return _minioClient.SetBucketPolicy(policyConfig)
}

func TempGetObject(objectConfig *minio_api.ObjectConfig, duration time.Duration) (*url.URL, error) {
	return _minioClient.TempGetObject(objectConfig, duration)
}

func TempPutObject(objectConfig *minio_api.ObjectConfig, duration time.Duration) (*url.URL, error) {
	return _minioClient.TempPutObject(objectConfig, duration)
}

func UpdateBucketQuota(bucketConfig *minio_api.BucketConfig) error {
	return _minioClient.UpdateBucketQuota(bucketConfig)
}

func WithContext(context context.Context) *minio_api.Client {
	return _minioClient.WithContext(context)
}
