// Package minio_inst/client.go was generated by codegen, do not modify it
package minio_inst

import (
	"github.com/Juminiy/kube/pkg/storage_api/minio_api"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func CreateAccessKey() (*credentials.Value, error) {
	return _minioClient.CreateAccessKey()
}

func CreateAccessPolicy(policyConfig *minio_api.PolicyConfig) error {
	return _minioClient.CreateAccessPolicy(policyConfig)
}

func CreateBucketPolicy(policyConfig *minio_api.PolicyConfig) error {
	return _minioClient.CreateBucketPolicy(policyConfig)
}

func CreateIDPUser(value *credentials.Value) error {
	return _minioClient.CreateIDPUser(value)
}

func DeleteAccessKey(_string string) error {
	return _minioClient.DeleteAccessKey(_string)
}

func DeleteAccessPolicy(policyConfig *minio_api.PolicyConfig) error {
	return _minioClient.DeleteAccessPolicy(policyConfig)
}

func DeleteIDPUser(_string string) error {
	return _minioClient.DeleteIDPUser(_string)
}

func MakeBucket(bucketConfig *minio_api.BucketConfig) error {
	return _minioClient.MakeBucket(bucketConfig)
}

func RemoveBucket(bucketConfig *minio_api.BucketConfig) error {
	return _minioClient.RemoveBucket(bucketConfig)
}

func UpdateBucketQuota(bucketConfig *minio_api.BucketConfig) error {
	return _minioClient.UpdateBucketQuota(bucketConfig)
}
